EXP_NAME: augment DMemSeg v2
SEED: 42

DATASET:
  datadir: /root/autodl-tmp/wafer_segmentation
  texture_source_dir: /root/autodl-tmp/dtd/images
  anomaly_mask_info: ./anomaly_mask.json
  target: null
  resize:
    - 256 # height
    - 256 # width
  structure_grid_size: 8
  transparency_range:
    - 0.5 # under bound
    - 1 # upper bound
  perlin_scale: 6
  min_perlin_scale: 0
  perlin_noise_threshold: 0.5

DATALOADER:
  batch_size: 8
  num_workers: 0

MEMORYBANK:
  nb_memory_sample: 30
  memory_size: 1024

MODEL:
  feature_extractor_name: resnet18

TRAIN:
  batch_size: 8
  epochs: 64
  num_training_steps: 5000
  l1_weight: 0.6
  focal_weight: 0.4
  entropy_weight: 1
  focal_alpha: null
  focal_gamma: 4
  epsilon: 1e-12
  threshold: 0.0005
  use_wandb: True

OPTIMIZER:
  lr: 0.003
  weight_decay: 0.0005

SCHEDULER:
  min_lr: 0.0001
  warmup_ratio: 0.1
  use_scheduler: True

LOG:
  log_interval: 1
  eval_interval: 100

RESULT:
  savedir: ./saved_model